name: Build and Deploy CVPrompt app

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  build-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #- name: Build and Push Docker image
      #  id: push
      #  uses: docker/build-push-action@v6
      #  with:
      #    push: false
      #    tags: ghcr.io/${{ github.repository }}:latest

  deploy-on-vps:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy Compose File to Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml"
          target: "cvprompt"
          overwrite: true
      - name: SSH to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd cvprompt
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d --no-deps --force-recreate
            docker image prune -a -f
            sleep 10
            curl -f http://127.0.0.1:8000/health || exit 1
